// Generated by gencpp from file audio_file_player/AudioFilePlayResult.msg
// DO NOT EDIT!


#ifndef AUDIO_FILE_PLAYER_MESSAGE_AUDIOFILEPLAYRESULT_H
#define AUDIO_FILE_PLAYER_MESSAGE_AUDIOFILEPLAYRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace audio_file_player
{
template <class ContainerAllocator>
struct AudioFilePlayResult_
{
  typedef AudioFilePlayResult_<ContainerAllocator> Type;

  AudioFilePlayResult_()
    : success(false)
    , reason()
    , total_time()  {
    }
  AudioFilePlayResult_(const ContainerAllocator& _alloc)
    : success(false)
    , reason(_alloc)
    , total_time()  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;

   typedef ros::Time _total_time_type;
  _total_time_type total_time;





  typedef boost::shared_ptr< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> const> ConstPtr;

}; // struct AudioFilePlayResult_

typedef ::audio_file_player::AudioFilePlayResult_<std::allocator<void> > AudioFilePlayResult;

typedef boost::shared_ptr< ::audio_file_player::AudioFilePlayResult > AudioFilePlayResultPtr;
typedef boost::shared_ptr< ::audio_file_player::AudioFilePlayResult const> AudioFilePlayResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::audio_file_player::AudioFilePlayResult_<ContainerAllocator1> & lhs, const ::audio_file_player::AudioFilePlayResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.reason == rhs.reason &&
    lhs.total_time == rhs.total_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::audio_file_player::AudioFilePlayResult_<ContainerAllocator1> & lhs, const ::audio_file_player::AudioFilePlayResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace audio_file_player

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63da86c1ec3bfb8b78f7e875747b385b";
  }

  static const char* value(const ::audio_file_player::AudioFilePlayResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63da86c1ec3bfb8bULL;
  static const uint64_t static_value2 = 0x78f7e875747b385bULL;
};

template<class ContainerAllocator>
struct DataType< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "audio_file_player/AudioFilePlayResult";
  }

  static const char* value(const ::audio_file_player::AudioFilePlayResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result information\n"
"# If it was successful\n"
"bool success\n"
"# If it wasn't reason why it wasn't\n"
"string reason\n"
"# Total time the file was playing\n"
"time total_time\n"
;
  }

  static const char* value(const ::audio_file_player::AudioFilePlayResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.reason);
      stream.next(m.total_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioFilePlayResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::audio_file_player::AudioFilePlayResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::audio_file_player::AudioFilePlayResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
    s << indent << "total_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.total_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUDIO_FILE_PLAYER_MESSAGE_AUDIOFILEPLAYRESULT_H
