// Generated by gencpp from file audio_file_player/AudioFilePlayFeedback.msg
// DO NOT EDIT!


#ifndef AUDIO_FILE_PLAYER_MESSAGE_AUDIOFILEPLAYFEEDBACK_H
#define AUDIO_FILE_PLAYER_MESSAGE_AUDIOFILEPLAYFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace audio_file_player
{
template <class ContainerAllocator>
struct AudioFilePlayFeedback_
{
  typedef AudioFilePlayFeedback_<ContainerAllocator> Type;

  AudioFilePlayFeedback_()
    : elapsed_played_time()  {
    }
  AudioFilePlayFeedback_(const ContainerAllocator& _alloc)
    : elapsed_played_time()  {
  (void)_alloc;
    }



   typedef ros::Time _elapsed_played_time_type;
  _elapsed_played_time_type elapsed_played_time;





  typedef boost::shared_ptr< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AudioFilePlayFeedback_

typedef ::audio_file_player::AudioFilePlayFeedback_<std::allocator<void> > AudioFilePlayFeedback;

typedef boost::shared_ptr< ::audio_file_player::AudioFilePlayFeedback > AudioFilePlayFeedbackPtr;
typedef boost::shared_ptr< ::audio_file_player::AudioFilePlayFeedback const> AudioFilePlayFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator1> & lhs, const ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.elapsed_played_time == rhs.elapsed_played_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator1> & lhs, const ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace audio_file_player

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8da3f4d23c993ec117df61a7ea32b30c";
  }

  static const char* value(const ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8da3f4d23c993ec1ULL;
  static const uint64_t static_value2 = 0x17df61a7ea32b30cULL;
};

template<class ContainerAllocator>
struct DataType< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "audio_file_player/AudioFilePlayFeedback";
  }

  static const char* value(const ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback about the amount of time the audio has been played\n"
"time elapsed_played_time\n"
"\n"
;
  }

  static const char* value(const ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.elapsed_played_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioFilePlayFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::audio_file_player::AudioFilePlayFeedback_<ContainerAllocator>& v)
  {
    s << indent << "elapsed_played_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.elapsed_played_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUDIO_FILE_PLAYER_MESSAGE_AUDIOFILEPLAYFEEDBACK_H
