// Auto-generated. Do not edit!

// (in-package audio_file_player.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class AudioFilePlayFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.elapsed_played_time = null;
    }
    else {
      if (initObj.hasOwnProperty('elapsed_played_time')) {
        this.elapsed_played_time = initObj.elapsed_played_time
      }
      else {
        this.elapsed_played_time = {secs: 0, nsecs: 0};
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type AudioFilePlayFeedback
    // Serialize message field [elapsed_played_time]
    bufferOffset = _serializer.time(obj.elapsed_played_time, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type AudioFilePlayFeedback
    let len;
    let data = new AudioFilePlayFeedback(null);
    // Deserialize message field [elapsed_played_time]
    data.elapsed_played_time = _deserializer.time(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'audio_file_player/AudioFilePlayFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8da3f4d23c993ec117df61a7ea32b30c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback about the amount of time the audio has been played
    time elapsed_played_time
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new AudioFilePlayFeedback(null);
    if (msg.elapsed_played_time !== undefined) {
      resolved.elapsed_played_time = msg.elapsed_played_time;
    }
    else {
      resolved.elapsed_played_time = {secs: 0, nsecs: 0}
    }

    return resolved;
    }
};

module.exports = AudioFilePlayFeedback;
