(cl:defpackage audio_file_player-msg
  (:use )
  (:export
   "<AUDIOFILEPLAYACTION>"
   "AUDIOFILEPLAYACTION"
   "<AUDIOFILEPLAYACTIONFEEDBACK>"
   "AUDIOFILEPLAYACTIONFEEDBACK"
   "<AUDIOFILEPLAYACTIONGOAL>"
   "AUDIOFILEPLAYACTIONGOAL"
   "<AUDIOFILEPLAYACTIONRESULT>"
   "AUDIOFILEPLAYACTIONRESULT"
   "<AUDIOFILEPLAYFEEDBACK>"
   "AUDIOFILEPLAYFEEDBACK"
   "<AUDIOFILEPLAYGOAL>"
   "AUDIOFILEPLAYGOAL"
   "<AUDIOFILEPLAYRESULT>"
   "AUDIOFILEPLAYRESULT"
  ))

