; Auto-generated. Do not edit!


(cl:in-package audio_file_player-msg)


;//! \htmlinclude AudioFilePlayFeedback.msg.html

(cl:defclass <AudioFilePlayFeedback> (roslisp-msg-protocol:ros-message)
  ((elapsed_played_time
    :reader elapsed_played_time
    :initarg :elapsed_played_time
    :type cl:real
    :initform 0))
)

(cl:defclass AudioFilePlayFeedback (<AudioFilePlayFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AudioFilePlayFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AudioFilePlayFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name audio_file_player-msg:<AudioFilePlayFeedback> is deprecated: use audio_file_player-msg:AudioFilePlayFeedback instead.")))

(cl:ensure-generic-function 'elapsed_played_time-val :lambda-list '(m))
(cl:defmethod elapsed_played_time-val ((m <AudioFilePlayFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader audio_file_player-msg:elapsed_played_time-val is deprecated.  Use audio_file_player-msg:elapsed_played_time instead.")
  (elapsed_played_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AudioFilePlayFeedback>) ostream)
  "Serializes a message object of type '<AudioFilePlayFeedback>"
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'elapsed_played_time)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'elapsed_played_time) (cl:floor (cl:slot-value msg 'elapsed_played_time)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AudioFilePlayFeedback>) istream)
  "Deserializes a message object of type '<AudioFilePlayFeedback>"
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'elapsed_played_time) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AudioFilePlayFeedback>)))
  "Returns string type for a message object of type '<AudioFilePlayFeedback>"
  "audio_file_player/AudioFilePlayFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AudioFilePlayFeedback)))
  "Returns string type for a message object of type 'AudioFilePlayFeedback"
  "audio_file_player/AudioFilePlayFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AudioFilePlayFeedback>)))
  "Returns md5sum for a message object of type '<AudioFilePlayFeedback>"
  "8da3f4d23c993ec117df61a7ea32b30c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AudioFilePlayFeedback)))
  "Returns md5sum for a message object of type 'AudioFilePlayFeedback"
  "8da3f4d23c993ec117df61a7ea32b30c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AudioFilePlayFeedback>)))
  "Returns full string definition for message of type '<AudioFilePlayFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback about the amount of time the audio has been played~%time elapsed_played_time~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AudioFilePlayFeedback)))
  "Returns full string definition for message of type 'AudioFilePlayFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback about the amount of time the audio has been played~%time elapsed_played_time~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AudioFilePlayFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AudioFilePlayFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AudioFilePlayFeedback
    (cl:cons ':elapsed_played_time (elapsed_played_time msg))
))
